schemaPath: schema.graphql
extensions:
  endpoints:
    default:
      url: 'http://localhost:${env:PORT}/graphql'
      subscription: 'ws://localhost:${env:PORT}'
    local:
      url: 'http://localhost:${env:PORT}/graphql'
      subscription: 'ws://localhost:${env:PORT}'